## WATER DATA ANALYSIS

#### https://help.waterdata.usgs.gov/faq/automated-retrievals

#### https://help.waterdata.usgs.gov/output-formats#Water_Use_html_table

In [1]:
import pandas as pd
import os
import csv
import re

notebook_path = os.path.abspath("water_data_use.txt")
cwd = os.getcwd()  # Get the current working directory (cwd)
files = os.listdir(cwd)  # Get all the files in that directory
print("Files in '%s': %s" % (cwd, files))

Files in '/Users/shhudspeth/water_data': ['water_use_data', 'water_data_2', 'Water Data Clean_Up Notebook.ipynb', '.ipynb_checkpoints']

In [2]:
#### The data from waterdata.usgs.gov is very ugly. It's a rdb file

In [3]:
fhand = open('water_use_data', 'r')

count=0
_list = []

for text in fhand:
    if not text.startswith("#"):
        count +=1
        _list.append(text)
count
_list[0]

'2s\t40s\t3s\t40s\t4s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\t16s\n'

In [39]:
_list[3]

'state_cd\tstate_name\tcounty_cd\tcounty_nm\tyear\tTotal Population total population of area, in thousands\tPublic Supply population served by groundwater, in thousands\tPublic Supply population served by surface water, in thousands\tPublic Supply total population served, in thousands\tPublic Supply self-supplied groundwater withdrawals, fresh, in Mgal/d\tPublic Supply self-supplied groundwater withdrawals, saline, in Mgal/d\tPublic Supply total self-supplied withdrawals, groundwater, in Mgal/d\tPublic Supply self-supplied surface-water withdrawals, fresh, in Mgal/d\tPublic Supply self-supplied surface-water withdrawals, saline, in Mgal/d\tPublic Supply total self-supplied withdrawals, surface water, in Mgal/d\tPublic Supply total self-supplied withdrawals, fresh, in Mgal/d\tPublic Supply total self-supplied withdrawals, saline, in Mgal/d\tPublic Supply total self-supplied withdrawals, total, in Mgal/d\tPublic Supply deliveries to domestic, in Mgal/d\tPublic Supply deliveries to commercial, in Mgal/d\tPublic Supply deliveries to industrial, in Mgal/d\tPublic Supply deliveries to thermoelectric, in Mgal/d\tPublic Supply total deliveries, in Mgal/d\tPublic Supply public use and losses, in Mgal/d\tPublic Supply per capita use, in gallons/person/day\tPublic Supply reclaimed wastewater, in Mgal/d\tPublic Supply number of facilities\tDomestic self-supplied groundwater withdrawals, fresh, in Mgal/d\tDomestic self-supplied groundwater withdrawals, saline, in Mgal/d\tDomestic total self-supplied withdrawals, groundwater, in Mgal/d\tDomestic self-supplied surface-water withdrawals, fresh, in Mgal/d\tDomestic self-supplied surface-water withdrawals, saline, in Mgal/d\tDomestic total self-supplied withdrawals, surface water, in Mgal/d\tDomestic total self-supplied withdrawals, fresh, in Mgal/d\tDomestic self-supplied population, in thousands\tDomestic deliveries from public supply, in Mgal/d\tDomestic total self-supplied withdrawals, saline, in Mgal/d\tDomestic per capita use, public-supplied, in gallons/person/day\tDomestic total self-supplied withdrawals, in Mgal/d\tDomestic total self-supplied withdrawals plus deliveries, in Mgal/d\tDomestic consumptive use, fresh, in Mgal/d\tDomestic consumptive use, saline, in Mgal/d\tDomestic total consumptive use, in Mgal/d\tDomestic per capita use, self-supplied, in gallons/person/day\tDomestic reclaimed wastewater, in Mgal/d\tCommercial self-supplied groundwater withdrawals, fresh, in Mgal/d\tCommercial self-supplied groundwater withdrawals, saline, in Mgal/d\tCommercial total self-supplied withdrawals, groundwater, in Mgal/d\tCommercial self-supplied surface-water withdrawals, fresh, in Mgal/d\tCommercial self-supplied surface-water withdrawals, saline, in Mgal/d\tCommercial total self-supplied withdrawals, surface water, in Mgal/d\tCommercial total self-supplied withdrawals, fresh, in Mgal/d\tCommercial total self-supplied withdrawals, saline, in Mgal/d\tCommercial total self-supplied withdrawals, in Mgal/d\tCommercial deliveries from public supply, in Mgal/d\tCommercial total self-supplied withdrawals plus deliveries, in Mgal/d\tCommercial consumptive use, fresh, in Mgal/d\tCommercial consumptive use, saline, in Mgal/d\tCommercial total consumptive use, in Mgal/d\tCommercial reclaimed wastewater, in Mgal/d\tIndustrial self-supplied groundwater withdrawals, fresh, in Mgal/d\tIndustrial self-supplied groundwater withdrawals, saline, in Mgal/d\tIndustrial total self-supplied withdrawals, groundwater, in Mgal/d\tIndustrial self-supplied surface-water withdrawals, fresh, in Mgal/d\tIndustrial self-supplied surface-water withdrawals, saline, in Mgal/d\tIndustrial total self-supplied withdrawals, surface water, in Mgal/d\tIndustrial total self-supplied withdrawals, fresh, in Mgal/d\tIndustrial total self-supplied withdrawals, saline, in Mgal/d\tIndustrial total self-supplied withdrawals, in Mgal/d\tIndustrial deliveries from public supply, in Mgal/d\tIndustrial total self-supplied withdrawals plus deliveries, in Mgal/d\tIndustrial consumptive use, fresh, in Mgal/d\tIndustrial consumptive use, saline, in Mgal/d\tIndustrial total consumptive use, in Mgal/d\tIndustrial reclaimed wastewater, in Mgal/d\tIndustrial number of facilities\tTotal Thermoelectric Power self-supplied groundwater withdrawals, fresh, in Mgal/d\tTotal Thermoelectric Power self-supplied groundwater withdrawals, saline, in Mgal/d\tTotal Thermoelectric Power total self-supplied withdrawals, groundwater, in Mgal/d\tTotal Thermoelectric Power self-supplied surface-water withdrawals, fresh, in Mgal/d\tTotal Thermoelectric Power self-supplied surface-water withdrawals, saline, in Mgal/d\tTotal Thermoelectric Power total self-supplied withdrawals, surface water, in Mgal/d\tTotal Thermoelectric Power total self-supplied withdrawals, fresh, in Mgal/d\tTotal Thermoelectric Power total self-supplied withdrawals, saline, in Mgal/d\tTotal Thermoelectric Power total self-supplied withdrawals, total, in Mgal/d\tTotal Thermoelectric Power total self-supplied withdrawals plus deliveries, in Mgal/d\tTotal Thermoelectric Power consumptive use, fresh, in Mgal/d\tTotal Thermoelectric Power consumptive use, saline, in Mgal/d\tTotal Thermoelectric Power total consumptive use, in Mgal/d\tTotal Thermoelectric Power power generated, in gigawatt-hours\tTotal Thermoelectric Power reclaimed wastewater, in Mgal/d\tTotal Thermoelectric Power number of facilities\tFossil-fuel Thermoelectric Power self-supplied groundwater withdrawals, fresh, in Mgal/d\tFossil-fuel Thermoelectric Power self-supplied groundwater withdrawals, saline, in Mgal/d\tFossil-fuel Thermoelectric Power total self-supplied withdrawals, groundwater, in Mgal/d\tFossil-fuel Thermoelectric Power self-supplied surface-water withdrawals, fresh, in Mgal/d\tFossil-fuel Thermoelectric Power self-supplied surface-water withdrawals, saline, in Mgal/d\tFossil-fuel Thermoelectric Power total self-supplied withdrawals, surface water, in Mgal/d\tFossil-fuel Thermoelectric Power total self-supplied withdrawals, fresh, in Mgal/d\tFossil-fuel Thermoelectric Power total self-supplied withdrawals, saline, in Mgal/d\tFossil-fuel Thermoelectric Power total self-supplied withdrawals, in Mgal/d\tFossil-fuel Thermoelectric Power deliveries from public supply, in Mgal/d\tFossil-fuel Thermoelectric Power total self-supplied withdrawals plus deliveries, in Mgal/d\tFossil-fuel Thermoelectric Power consumptive use, fresh, in Mgal/d\tFossil-fuel Thermoelectric Power consumptive use, saline, in Mgal/d\tFossil-fuel Thermoelectric Power total consumptive use, in Mgal/d\tFossil-fuel Thermoelectric Power power generation, in gigawatt-hours\tFossil-fuel Thermoelectric Power reclaimed wastewater, in Mgal/d\tFossil-fuel Thermoelectric Power number of facilities\tGeothermal Thermoelectric Power self-supplied groundwater withdrawals, fresh, in Mgal/d\tGeothermal Thermoelectric Power self-supplied groundwater withdrawals, saline, in Mgal/d\tGeothermal Thermoelectric Power total self-supplied withdrawals, groundwater, in Mgal/d\tGeothermal Thermoelectric Power self-supplied surface-water withdrawals, fresh, in Mgal/d\tGeothermal Thermoelectric Power self-supplied surface-water withdrawals, saline, in Mgal/d\tGeothermal Thermoelectric Power total self-supplied withdrawals, surface water, in Mgal/d\tGeothermal Thermoelectric Power total self-supplied withdrawals, fresh, in Mgal/d\tGeothermal Thermoelectric Power total self-supplied withdrawals, saline, in Mgal/d\tGeothermal Thermoelectric Power total self-supplied withdrawals, in Mgal/d\tGeothermal Thermoelectric Power deliveries from public supply, in Mgal/d\tGeothermal Thermoelectric Power total self-supplied withdrawals plus deliveries, in Mgal/d\tGeothermal Thermoelectric Power consumptive use, fresh, in Mgal/d\tGeothermal Thermoelectric Power consumptive use, saline, in Mgal/d\tGeothermal Thermoelectric Power total consumptive use, in Mgal/d\tGeothermal Thermoelectric Power power generation, in gigawatt-hours\tGeothermal Thermoelectric Power reclaimed wastewater, in Mgal/d\tGeothermal Thermoelectric Power number of facilities\tNuclear Thermoelectric Power self-supplied groundwater withdrawals, fresh, in Mgal/d\tNuclear Thermoelectric Power self-supplied groundwater withdrawals, saline, in Mgal/d\tNuclear Thermoelectric Power total self-supplied withdrawals, groundwater, in Mgal/d\tNuclear Thermoelectric Power self-supplied surface-water withdrawals, fresh, in Mgal/d\tNuclear Thermoelectric Power self-supplied surface-water withdrawals, saline, in Mgal/d\tNuclear Thermoelectric Power total self-supplied withdrawals, surface water, in Mgal/d\tNuclear Thermoelectric Power total self-supplied withdrawals, fresh, in Mgal/d\tNuclear Thermoelectric Power total self-supplied withdrawals, saline, in Mgal/d\tNuclear Thermoelectric Power total self-supplied withdrawals, in Mgal/d\tNuclear Thermoelectric Power deliveries from public supply, in Mgal/d\tNuclear Thermoelectric Power total self-supplied withdrawals plus deliveries, in Mgal/d\tNuclear Thermoelectric Power consumptive use, fresh, in Mgal/d\tNuclear Thermoelectric Power consumptive use, saline, in Mgal/d\tNuclear Thermoelectric Power total consumptive use, in Mgal/d\tNuclear Thermoelectric Power power generation, in gigawatt-hours\tNuclear Thermoelectric Power reclaimed wastewater, in Mgal/d\tNuclear Thermoelectric Power number of facilities\tThermoelectric Power (Once-through cooling) self-supplied groundwater withdrawals, fresh, in Mgal/d\tThermoelectric Power (Once-through cooling) self-supplied groundwater withdrawals, saline, in Mgal/d\tThermoelectric Power (Once-through cooling) total self-supplied withdrawals, groundwater, in Mgal/d\tThermoelectric Power (Once-through cooling) self-supplied surface-water withdrawals, fresh, in Mgal/\tThermoelectric Power (Once-through cooling) self-supplied surface-water withdrawals, saline, in Mgal\tThermoelectric Power (Once-through cooling) total self-supplied withdrawals, surface water, in Mgal/\tThermoelectric Power (Once-through cooling) total self-supplied withdrawals, fresh, in Mgal/d\tThermoelectric Power (Once-through cooling) total self-supplied withdrawals, saline, in Mgal/d\tThermoelectric Power (Once-through cooling) total self-supplied withdrawals, total, in Mgal/d\tThermoelectric Power (Once-through cooling) deliveries from public supply, in Mgal/d\tThermoelectric Power (Once-through cooling) total self-supplied withdrawals plus deliveries, in Mgal\tThermoelectric Power (Once-through cooling) consumptive use, fresh, in Mgal/d\tThermoelectric Power (Once-through cooling) consumptive use, saline, in Mgal/d\tThermoelectric Power (Once-through cooling) total consumptive use, in Mgal/d\tThermoelectric Power (Once-through cooling) power generated, in gigawatt-hours\tThermoelectric Power (Once-through cooling) reclaimed wastewater, in Mgal/d\tThermoelectric Power (Once-through cooling) number of facilities\tThermoelectric Power (Closed-loop cooling) self-supplied groundwater withdrawals, fresh, in Mgal/d\tThermoelectric Power (Closed-loop cooling) self-supplied groundwater withdrawals, saline, in Mgal/d\tThermoelectric Power (Closed-loop cooling) total self-supplied withdrawals, groundwater, in Mgal/d\tThermoelectric Power (Closed-loop cooling) self-supplied surface-water withdrawals, fresh, in Mgal/d\tThermoelectric Power (Closed-loop cooling) self-supplied surface-water withdrawals, saline, in Mgal/\tThermoelectric Power (Closed-loop cooling) total self-supplied withdrawals, surface water, in Mgal/d\tThermoelectric Power (Closed-loop cooling) total self-supplied withdrawals, fresh, in Mgal/d\tThermoelectric Power (Closed-loop cooling) total self-supplied withdrawals, saline, in Mgal/d\tThermoelectric Power (Closed-loop cooling) total self-supplied withdrawals, total, in Mgal/d\tThermoelectric Power (Closed-loop cooling) deliveries from public supply, in Mgal/d\tThermoelectric Power (Closed-loop cooling) total self-supplied withdrawals plus deliveries, in Mgal/\tThermoelectric Power (Closed-loop cooling) consumptive use, fresh, in Mgal/d\tThermoelectric Power (Closed-loop cooling) consumptive use, saline, in Mgal/d\tThermoelectric Power (Closed-loop cooling) total consumptive use, in Mgal/d\tThermoelectric Power (Closed-loop cooling) power generated, in gigawatt-hours\tThermoelectric Power (Closed-loop cooling) reclaimed wastewater, in Mgal/d\tThermoelectric Power (Closed-loop cooling) number of facilities\tMining self-supplied groundwater withdrawals, fresh, in Mgal/d\tMining self-supplied groundwater withdrawals, saline, in Mgal/d\tMining total self-supplied withdrawals, groundwater, in Mgal/d\tMining self-supplied surface-water withdrawals, fresh, in Mgal/d\tMining self-supplied surface-water withdrawals, saline, in Mgal/d\tMining total self-supplied withdrawals, surface water, in Mgal/d\tMining total self-supplied withdrawals, fresh, in Mgal/d\tMining total self-supplied withdrawals, saline, in Mgal/d\tMining total self-supplied withdrawals, in Mgal/d\tMining consumptive use, fresh, in Mgal/d\tMining consumptive use, saline, in Mgal/d\tMining total consumptive use, in Mgal/d\tMining reclaimed wastewater, in Mgal/d\tLivestock self-supplied groundwater withdrawals, fresh, in Mgal/d\tLivestock self-supplied surface-water withdrawals, fresh, in Mgal/d\tLivestock total self-supplied withdrawals, fresh, in Mgal/d\tLivestock consumptive use, fresh, in Mgal/d\tLivestock (Stock) self-supplied groundwater withdrawals, fresh, in Mgal/d\tLivestock (Stock) self-supplied groundwater withdrawals, saline, in Mgal/d\tLivestock (Stock) total self-supplied withdrawals, groundwater, in Mgal/d\tLivestock (Stock) self-supplied surface-water withdrawals, fresh, in Mgal/d\tLivestock (Stock) self-supplied surface-water withdrawals, saline, in Mgal/d\tLivestock (Stock) total self-supplied withdrawals, surface water, in Mgal/d\tLivestock (Stock) total self-supplied withdrawals, fresh, in Mgal/d\tLivestock (Stock) total self-supplied withdrawals, saline, in Mgal/d\tLivestock (Stock) total self-supplied withdrawals, in Mgal/d\tLivestock (Stock) consumptive use, fresh, in Mgal/d\tLivestock (Stock) consumptive use, saline, in Mgal/d\tLivestock (Stock) total consumptive use, in Mgal/d\tLivestock (Animal Specialties) self-supplied groundwater withdrawals, fresh, in Mgal/d\tLivestock (Animal Specialties) self-supplied groundwater withdrawals, saline, in Mgal/d\tLivestock (Animal Specialties) total self-supplied withdrawals, groundwater, in Mgal/d\tLivestock (Animal Specialties) self-supplied surface-water withdrawals, fresh, in Mgal/d\tLivestock (Animal Specialties) self-supplied surface-water withdrawals, saline, in Mgal/d\tLivestock (Animal Specialties) total self-supplied withdrawals, surface water, in Mgal/d\tLivestock (Animal Specialties) total self-supplied withdrawals, fresh, in Mgal/d\tLivestock (Animal Specialties) total self-supplied withdrawals, saline, in Mgal/d\tLivestock (Animal Specialties) total self-supplied withdrawals, in Mgal/d\tLivestock (Animal Specialties) consumptive use, fresh, in Mgal/d\tLivestock (Animal Specialties) consumptive use, saline, in Mgal/d\tLivestock (Animal Specialties) total consumptive use, in Mgal/d\tAquaculture self-supplied groundwater withdrawals, fresh, in Mgal/d\tAquaculture self-supplied groundwater withdrawals, saline, in Mgal/d\tAquaculture total self-supplied withdrawals, groundwater, in Mgal/d\tAquaculture self-supplied surface-water withdrawals, fresh, in Mgal/d\tAquaculture self-supplied surface-water withdrawals, saline, in Mgal/d\tAquaculture total self-supplied withdrawals, surface water, in Mgal/d\tAquaculture total self-supplied withdrawals, fresh, in Mgal/d\tAquaculture total self-supplied withdrawals, saline, in Mgal/d\tAquaculture total self-supplied withdrawals, in Mgal/d\tAquaculture consumptive use, fresh, in Mgal/d\tAquaculture consumptive use, saline, in Mgal/d\tAquaculture total consumptive use, in Mgal/d\tIrrigation, Total self-supplied groundwater withdrawals, fresh, in Mgal/d\tIrrigation, Total self-supplied groundwater withdrawals, saline, in Mgal/d\tIrrigation, Total total self-supplied withdrawals, groundwater, in Mgal/d\tIrrigation, Total self-supplied surface-water withdrawals, fresh, in Mgal/d\tWastewater Treatment reclaimed wastewater released by public wastewater facilities, in Mgal/d\tIrrigation, Total self-supplied surface-water withdrawals, saline, in Mgal/d\tIrrigation, Total total self-supplied withdrawals, surface water, in Mgal/d\tIrrigation, Total total self-supplied withdrawals, fresh, in Mgal/d\tIrrigation, Total total self-supplied withdrawals, saline, in Mgal/d\tIrrigation, Total total self-supplied withdrawals, in Mgal/d\tIrrigation, Total consumptive use, fresh, in Mgal/d\tIrrigation, Total consumptive use, saline, in Mgal/d\tIrrigation, Total total consumptive use, in Mgal/d\tIrrigation, Total conveyance loss, in Mgal/d\tIrrigation, Total sprinkler irrigation, in thousand acres\tIrrigation, Total microirrigation, in thousand acres\tIrrigation, Total surface irrigation, in thousand acres\tIrrigation, Total total irrigation, in thousand acres\tIrrigation, Total reclaimed wastewater, in Mgal/d\tIrrigation, Crop self-supplied groundwater withdrawals for crops, fresh, in Mgal/d\tIrrigation, Crop self-supplied surface-water withdrawals for crops, fresh, in Mgal/d\tIrrigation, Crop total self-supplied withdrawals for crops, fresh, in Mgal/d\tIrrigation, Crop consumptive use for crops, fresh, in Mgal/d\tIrrigation, Crop conveyance loss for crops, in Mgal/d\tIrrigation, Crop sprinkler irrigation for crops, in thousand acres\tIrrigation, Crop microirrigation for crops, in thousand acres\tIrrigation, Crop surface irrigation for crops, in thousand acres\tIrrigation, Crop total irrigation for crops, in thousand acres\tIrrigation, Crop reclaimed wastewater for crops, in Mgal/d\tIrrigation, Golf Courses self-supplied groundwater withdrawals for golf courses, fresh, in Mgal/d\tIrrigation, Golf Courses self-supplied surface-water withdrawals for golf courses, fresh, in Mgal/d\tIrrigation, Golf Courses total self-supplied withdrawals for golf courses, fresh, in Mgal/d\tIrrigation, Golf Courses consumptive use for golf courses, fresh, in Mgal/d\tIrrigation, Golf Courses conveyance loss for golf courses, in Mgal/d\tIrrigation, Golf Courses sprinkler irrigation for golf courses, in thousand acres\tIrrigation, Golf Courses microirrigation for golf courses, in thousand acres\tIrrigation, Golf Courses surface irrigation for golf courses, in thousand acres\tIrrigation, Golf Courses total irrigation for golf courses, in thousand acres\tIrrigation, Golf Courses reclaimed wastewater for golf courses, in Mgal/d\tHydroelectric Power instream water use, in Mgal/d\tHydroelectric Power offstream surface-water withdrawals, fresh, in Mgal/d\tHydroelectric Power surface water self-supplied offstream withdrawals, saline, in Mgal/d\tHydroelectric Power total offstream surface-water withdrawals in Mgal/d\tHydroelectric Power power generated by instream use, in gigawatt-hours\tHydroelectric Power power generated by offstream use, in gigawatt-hours\tHydroelectric Power total power generated, in gigawatt-hours\tHydroelectric Power number of instream facilities\tHydroelectric Power number of offstream facilities\tHydroelectric Power total number of facilities\tWastewater Treatment returns by public wastewater facilities, in Mgal/d\tWastewater Treatment number of public wastewater facilities\tWastewater Treatment number of wastewater facilities\tWastewater Treatment reclaimed wastewater released by wastewater facilities, in Mgal/d\n'

In [13]:
import re

count =2
dict_w = {}
for row in _list[2:]:
    dict_w[count] = re.findall('(.*?)s*[\t]', _list[count])
    item_ = []
    for item in dict_w[count]:
        item = item.replace('-', '0')
        item_.append(item)
    
    dict_w[count] = item_
        
    
    #print(dict_w[count])
    count += 1

In [14]:
# checking that each entry in dictionary is the same length in order to add to data frame
for item in dict_w.values():
    if len(item) != 282:
        print("NOT ENOUGH ENTRIES ")

In [15]:
len(dict_w)

408

In [16]:
df= pd.DataFrame(data = dict_w)

In [17]:
df = df.transpose().reset_index()

In [22]:
count_= 0
column_dict = {}
for item in dict_w[2]:
    #print(item)
    column_dict[count] = item
    count += 1

len(column_dict)

282

In [29]:
df = df.rename(columns=df.iloc[0])

In [30]:
    
df.drop(columns=['index'], inplace=True)

KeyError: "['index'] not found in axis"

In [31]:
df.head()

,state_cd,state_name,county_cd,county_nm,year,"Total Population total population of area, in thousand","Public Supply population served by groundwater, in thousand","Public Supply population served by surface water, in thousand","Public Supply total population served, in thousand","Public Supply self0supplied groundwater withdrawals, fresh, in Mgal/d",...,Hydroelectric Power total offstream surface0water withdrawals in Mgal/d,"Hydroelectric Power power generated by instream use, in gigawatt0hour","Hydroelectric Power power generated by offstream use, in gigawatt0hour","Hydroelectric Power total power generated, in gigawatt0hour",Hydroelectric Power number of instream facilitie,Hydroelectric Power number of offstream facilitie,Hydroelectric Power total number of facilitie,"Wastewater Treatment returns by public wastewater facilities, in Mgal/d",Wastewater Treatment number of public wastewater facilitie,Wastewater Treatment number of wastewater facilitie
0,state_cd,state_name,county_cd,county_nm,year,"Total Population total population of area, in ...",Public Supply population served by groundwater...,Public Supply population served by surface wat...,"Public Supply total population served, in thou...",Public Supply self0supplied groundwater withdr...,...,Hydroelectric Power total offstream surface0wa...,Hydroelectric Power power generated by instrea...,Hydroelectric Power power generated by offstre...,"Hydroelectric Power total power generated, in ...",Hydroelectric Power number of instream facilitie,Hydroelectric Power number of offstream facilitie,Hydroelectric Power total number of facilitie,Wastewater Treatment returns by public wastewa...,Wastewater Treatment number of public wastewat...,Wastewater Treatment number of wastewater faci...
1,2,40,3,40,4,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
2,06,California,001,Alameda County,1985,1195.160,185.950,967.160,1153.110,31.58,...,0,0.00,0,0,0,0,0,142.32,7,0
3,06,California,001,Alameda County,1990,1279.180,109.370,1142.440,1251.810,23.83,...,0,0.00,0,0,0,0,0,134.59,8,0
4,06,California,001,Alameda County,1995,1347.700,165.830,1162.820,1328.650,31.05,...,0.00,0.00,0.00,0.00,0,0,0,154.15,8,0

In [32]:
df = df[1:]

In [33]:
df.shape

(407, 282)

In [34]:
df.to_csv('water_data.csv')

In [35]:
df.describe()

,state_cd,state_name,county_cd,county_nm,year,"Total Population total population of area, in thousand","Public Supply population served by groundwater, in thousand","Public Supply population served by surface water, in thousand","Public Supply total population served, in thousand","Public Supply self0supplied groundwater withdrawals, fresh, in Mgal/d",...,Hydroelectric Power total offstream surface0water withdrawals in Mgal/d,"Hydroelectric Power power generated by instream use, in gigawatt0hour","Hydroelectric Power power generated by offstream use, in gigawatt0hour","Hydroelectric Power total power generated, in gigawatt0hour",Hydroelectric Power number of instream facilitie,Hydroelectric Power number of offstream facilitie,Hydroelectric Power total number of facilitie,"Wastewater Treatment returns by public wastewater facilities, in Mgal/d",Wastewater Treatment number of public wastewater facilitie,Wastewater Treatment number of wastewater facilitie
count,407,407,407,407,407,407,407,407,407,407,...,407,407,407,407,407,407,407,407,407,407
unique,2,2,59,59,8,403,331,309,403,365,...,30,89,30,37,18,13,17,174,42,2
top,06,California,067,Ventura County,2015,3.390,0,0,0.600,0.00,...,0,0,0,0,0,0,0,0,0,0
freq,406,406,7,7,58,2,58,58,2,11,...,348,232,348,348,351,379,372,232,232,406

In [36]:
df.head(20)

,state_cd,state_name,county_cd,county_nm,year,"Total Population total population of area, in thousand","Public Supply population served by groundwater, in thousand","Public Supply population served by surface water, in thousand","Public Supply total population served, in thousand","Public Supply self0supplied groundwater withdrawals, fresh, in Mgal/d",...,Hydroelectric Power total offstream surface0water withdrawals in Mgal/d,"Hydroelectric Power power generated by instream use, in gigawatt0hour","Hydroelectric Power power generated by offstream use, in gigawatt0hour","Hydroelectric Power total power generated, in gigawatt0hour",Hydroelectric Power number of instream facilitie,Hydroelectric Power number of offstream facilitie,Hydroelectric Power total number of facilitie,"Wastewater Treatment returns by public wastewater facilities, in Mgal/d",Wastewater Treatment number of public wastewater facilitie,Wastewater Treatment number of wastewater facilitie
1,2,40,3,40,4,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
2,06,California,001,Alameda County,1985,1195.160,185.950,967.160,1153.110,31.58,...,0,0.00,0,0,0,0,0,142.32,7,0
3,06,California,001,Alameda County,1990,1279.180,109.370,1142.440,1251.810,23.83,...,0,0.00,0,0,0,0,0,134.59,8,0
4,06,California,001,Alameda County,1995,1347.700,165.830,1162.820,1328.650,31.05,...,0.00,0.00,0.00,0.00,0,0,0,154.15,8,0
5,06,California,001,Alameda County,2000,1443.740,152.460,1114.420,1266.880,26.70,...,0,0,0,0,0,0,0,0,0,0
6,06,California,001,Alameda County,2005,1448.905,477.712,955.782,1433.494,52.19,...,0,0,0,0,0,0,0,0,0,0
7,06,California,001,Alameda County,2010,1510.271,0.780,1447.920,1448.700,19.01,...,0,0,0,0,0,0,0,0,0,0
8,06,California,001,Alameda County,2015,1638.215,0,0,1629.900,17.63,...,0,0,0,0,0,0,0,0,0,0
9,06,California,003,Alpine County,1985,1.200,0.430,0.550,0.980,0.07,...,0,0.00,0,0,0,0,0,4.27,4,0
10,06,California,003,Alpine County,1990,1.110,0.350,0.250,0.600,0.09,...,0,0.00,0,0,0,0,0,0.12,3,0
11,06,California,003,Alpine County,1995,1.170,0.280,0.620,0.900,0.05,...,0.00,0.00,0.00,0.00,0,0,0,0.15,3,0
12,06,California,003,Alpine County,2000,1.210,0.150,0.450,0.600,0.06,...,0,0,0,0,0,0,0,0,0,0
13,06,California,003,Alpine County,2005,1.159,0.076,0.244,0.320,0.01,...,0,0,0,0,0,0,0,0,0,0
14,06,California,003,Alpine County,2010,1.175,0.220,0.530,0.750,0.08,...,0,0,0,0,0,0,0,0,0,0
15,06,California,003,Alpine County,2015,1.110,0,0,0.705,0.03,...,0,0,0,0,0,0,0,0,0,0
16,06,California,005,Amador County,1985,22.890,3.870,8.670,12.540,0.61,...,0,994.86,0,0,0,0,0,1.52,7,0
17,06,California,005,Amador County,1990,30.040,3.540,19.610,23.150,0.36,...,0,764.21,0,0,4,0,0,1.25,7,0
18,06,California,005,Amador County,1995,32.600,1.770,24.930,26.700,0.35,...,2316.32,0.00,1207.58,1207.58,0,5,5,1.76,7,0
19,06,California,005,Amador County,2000,35.100,2.460,24.360,26.820,0.54,...,0,0,0,0,0,0,0,0,0,0
20,06,California,005,Amador County,2005,38.471,0.425,19.800,20.225,0.13,...,0,0,0,0,0,0,0,0,0,0